- name: Install docker
  hosts: web_server
  become: true
  roles:
    - role: docker
      vars:
        docker_user: "{{ ansible_user }}"
        arch_mapping:
          x86_64: amd64
          aarch64: arm64


- name: Configure Nginx as reverse proxy
  hosts: proxy_server
  become: true
  roles:
    - role: nginx_proxy
      vars:
        nginx_config_dir: /home/nginx
        nginx_config_file: reverse_proxy.conf
        web_port: 5000
        domain_name: myapp.com
