---

- name: Create directory for nginx config
  ansible.builtin.file:
    path: "{{ nginx_config_dir }}"
    state: directory
    mode: '0755'

- name: Template the nginx reverse proxy config
  ansible.builtin.template:
    src: reverse_proxy.conf.j2
    dest: "{{ nginx_config_dir }}/{{ nginx_config_file }}"
    mode: '0644'

- name: Run nginx container as reverse proxy
  community.docker.docker_container:
    name: reverse-proxy
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - "{{ nginx_config_dir }}/{{ nginx_config_file }}:/etc/nginx/conf.d/default.conf"
