name: Docker Build and Push to Dockerhub and run Ansible playbook to deploy

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vm-info-app:${{ github.sha }}

    - name: Run Ansible playbook to deploy on VMs
      run: |
        ansible-playbook -i ./ansible/inventory ./ansible/playbooks/deploy_app.yml -e "commit_hash=$(git rev-parse HEAD)"